### ISSUE TITLE
What do _link_subdirs and _unlink_subdirs do in the /bin/dotfiles script?

### ISSUE THREAD

**Issue by ntwk** [milkypostman/dotfiles#1]
I picked up this script as a means of deploying and managing my own dotfiles but I am still trying to figure out what _link_subdirs and _unlink_subdirs do.  What are these functions for?  How are they meant to be used?

**Comment by milkypostman** [comment]
the idea is to check this repo out into $HOME/.dotfiles and then run the
dotfiles script to link all dotfiles into the actual $HOME directory.

**Comment by ntwk** [comment]
I've successfully used it to create symlinks but as I stepped through the '/bin/dotfiles' script to better understand things, I was stumped by the two aforementioned bash functions.  In line 47 of /bin/dotfiles I see the following bit of process substitution:
   
`<(find ${basedir} -mindepth 2 -maxdepth 2 -name .git)`

Why is it looking for a .git directory as a specific depth?

**Comment by milkypostman** [comment]
That is because rather than deal with submodules I just manually (or by the
'bootstrap' script) check out git directories into the .dotfiles directory.
So not only do I need to do 'git ls-files' on my .dotfiles directory, but I
also need to do it on the git repos that I checkout. So basically, it's
finding all the subdirectories that are also git repos. And I don't want it
it go any lower than subdirectories of the .dotfiles directory.

**Comment by ntwk** [comment]
Gotcha.  My first guess what that this somehow related to potential submodules.  The '/bin/bootstrap' script makes things more clear.  Thanks!
